### ISSUE TITLE
arviz

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/imas2xarray#20]
Arviz is a useful tool for visualizing xarray statistics. We should provide a script or notebook to show how imas2xarray data can be visualized in arviz.

https://python.arviz.org/en/stable/examples/index.html

**Comment by v1kko** [comment]
It might also replace the `merge` workflow we have, as it instead can use all data to visualize statistics

**Comment by v1kko** [comment]
closing due to insufficient time
